#pragma once
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <Windows.h>
#include <sqlite3.h>
#include "cJSON.h"
#include "cJSON_Utils.h"
#include "mystring.h"
#include "mynet.h"
